### PR TITLE
Update Microsoft.SqlServer.DacFx to 162.3.563 and fix dependencies

### PR DESCRIPTION
**Pull request by amizyak**
Update Microsoft.SqlServer.DacFx to 162.3.563 and fix dependencies

### CODE REVIEW

**Comment by t-johnson** [comment]
@amizyak thanks for this.

its quite an interesting issue, and looks to be because of the change made in the DacFx at this version - the [documenation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dac.deployment.deploymentplanmodifier.addbefore?view=sql-dacfx-162#microsoft-sqlserver-dac-deployment-deploymentplanmodifier-addbefore(microsoft-sqlserver-dac-deployment-deploymentplanhandle-microsoft-sqlserver-dac-deployment-deploymentstep-microsoft-sqlserver-dac-deployment-deploymentstep)) shows DeploymentPlanModifier.AddBefore Method as an instance method, but it looks to have been made static as of this version.

**Comment by t-johnson** [comment]
i've approved this PR even though the pipelines are failing - the failure is unrelated to this minor change.

**Comment by yelochka** [comment]
@t-johnson Are you planning to create a new release for this fix? as the latest one is still from last year.

**Comment by t-johnson** [comment]
probably will get to this before the end of the week...

**Comment by dzsquared** [comment]
we have a hotfix coming, if you can hold off a few more days - https://github.com/microsoft/DacFx/issues/461

**Comment by dzsquared** [comment]
hotfix is out, 162.3.566

**Pull request merged**
