### PR TITLE
Fixes #25 (gets the main branch back into a syntax-error-free state)

### LINKED ISSUE #25: Master branch does not build - A local variable or function named 'match' is already defined
I am guessing a merge issue but downloaded the latest source and project does not build. 

Severity	Code	Description	Project	File	Line	Suppression State	Tool
Error	CS0128	A local variable or function named 'match' is already defined in this scope	AgileSqlClub.SqlPackageFilter	.. CommandLineFilterParser.cs	78	Active	Compiler

image

### PR DESCRIPTION
**Pull request by t-johnson**
Fixes #25 which seems to have been the result of a bad merge.

Added and improved some tests to ensure that functionality was not lost.

### CODE REVIEW

**Comment by t-johnson** [comment]
@GoEddie any chance you're going to merge this?

**Comment by GoEddie** [comment]
@t-johnson thanks! Sorry for taking so long.

**Comment by GoEddie** [comment]
I haven’t used this for years, if you fancy becoming a committer for this let me know!

**Comment by t-johnson** [comment]
Sure thing. We use this where I work, so I have a vested interest in making sure it stays updated with latest sql server versions and such things.

**Comment by GoEddie** [comment]
Great, I’ve invited you - hopefully this will let you merge etc! Thanks for this, if you have any questions give me a shout :)

**Pull request merged**
